### PR TITLE
Convert unicode symbols to HTML chars

### PR DESCRIPTION
**Pull request by voiddragon**
Some feeds have unicode symbols in them, this converts them to their respective html chars.

### CODE REVIEW

**Comment by matagus** [comment]
Excellent! Can you rebase it so I can merge?

**Comment by voiddragon** [comment]
I've updated it with the new code along with some other problematic areas that came up. 

It's been a really long time since I've touched this, do let me know if there is a better way to handle this.

**Comment by matagus** [comment]
mmm there're 4 commits now and it doesn't pass the tests :/

maybe it'd be easier if you re-clone the repo, make a new branch and redo this change and submit a new PR?

**Comment by voiddragon** [comment]
Sure

**Pull request closed without merging**
